### ISSUE TITLE
How to check if Redis connection is established

### ISSUE THREAD

**Issue by TakhirMamirov** [glav/Glav.CacheAdapter#11]
I'm trying to set up Redis caching with the following configuration:

```
    <add key="Cache.CacheToUse" value="redis" />
    <add key="Cache.IsCacheEnabled" value="true" />
    <add key="Cache.CacheDurationInSeconds" value="300" />    
    <add key="Cache.LoggingLevel" value="Information"/>
    <add key="Cache.DistributedCacheServers" value="sample.redis.cache.windows.net:6379" />
    <add key="Cache.CacheSpecificData" value="ssl=false;abortConnect=false;connecttimeout=15000;password={mypass}" />
```

When I then call AppServices.Cache.GetAsync() with lambda, my lambda is being called all the time, as there is no cache. If I change server name, or pass - nothing is changed, no exception, error or timeout. And if I then go to Azure Redis CLI and type "GET {mycachekey}", then {nil} is returned.

So I'm not sure whether my app is really connected to Azure Redis or not. How can I check it?

**Comment by glav** [comment]
If there is no cache, an exception should be thrown. This is then written to whatever logging mechanism is configured.

See: https://github.com/glav/Glav.CacheAdapter/blob/2c90c00433d21cd1c20304b82ceedfc7650cc6a0/Glav.CacheAdapter/Distributed/Redis/RedisCacheAdapter.cs#L62

By default this is the System.Diagnostics.Trace mechanism but can be changed by calling the AppServices.SetLogger
