### ISSUE TITLE
Changing to .NET Standard

### ISSUE THREAD

**Issue by katrash** [glav/Glav.CacheAdapter#12]
Are there any plans to convert to .NET standard?

**Comment by glav** [comment]
Not immediately no. Unless demand requires it though. If enough people want it, then sure. However, it feels a little redundant given that there is an IDistributedCache interface with implementation for Redis, SQlServer and Memory I think (see: [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.distributed.idistributedcache?view=aspnetcore-2.2)
At best it would be an intermediary into this interface which feels like adding uneccessary complexity. Happy to hear others thoughts tho.

**Comment by katrash** [comment]
Thanks for the reply and the hint. I think the `IDistributedCache` interface and Microsoft extensions implementations will be sufficient.
