### ISSUE TITLE
Issue with CreatePackage.cmd script(s)

### ISSUE THREAD

**Issue by gep13** [glav/Glav.CacheAdapter#21]
As mentioned in this comment here:

https://github.com/glav/Glav.CacheAdapter/issues/3#issuecomment-804079020

There seems to be a small issue with the `CreatePackage.cmd` script.  When I ran this on my local machine, after building in `Release` mode in Visual Studio, I got the following output:

![image](https://user-images.githubusercontent.com/1271146/112046471-fc7c3400-8b43-11eb-9faa-2f8fb5088319.png)

The problem here being that the `lib\net472` folder doesn't exist, so the copy command isn't able to complete.

There are multiple ways that this "could" be fixed, so I won't create a PR for it, as I don't know how you would like to move forward with addressing it.  If you let me know how you want to proceed, I would be happy to submit a PR, so that we can get a new release pushed to NuGet.org.

**Comment by glav** [comment]
Ok, this sould be resolved now. Sorry about that. Must have been a PEBKAC issue :(

**Comment by gep13** [comment]
@glav thanks for getting this updated again!  I am very happy to confirm that the new 4.3.2 package is working as expected! 👍🏻
