### ISSUE TITLE
How to - Use Memcached with MemcachedCloud (RedisLabs) that requires user/pass

### ISSUE THREAD

**Issue by glav** [glav/Glav.CacheAdapter#3]
There is this nice article out there (https://redislabs.com/memcached-appharbor), but I don't know how to give username and password specifically to Cache.CacheSpecificData. How does one do that?

I'd prefer not to pull out Glav.CacheAdapter and go straight to Enyim to get SASL functionality.

Originally reported by @ferventcoder on Bitbucket at https://bitbucket.org/glav/cacheadapter/issues/39/how-to-use-memcached-with-memcachedcloud

**Comment by gep13** [comment]
@glav would you be wiling to accept a Pull Request which added this functionality into your library?  Thanks

**Comment by glav** [comment]
Absolutely! Totally welcome PR's

**Comment by glav** [comment]
Wow, I totally forgot about this issue too. It has been so long. Please submit a PR and I'd happily merge in.

**Comment by gep13** [comment]
@glav thanks for getting back to me! I really appreciate it!

I have created a PR here: https://github.com/glav/Glav.CacheAdapter/pull/19 which uses work that was originally completed by @ferventcoder, and I am putting it up for review, and hopefully merge into the code base.

Please let me know if you have any questions.

**Comment by gep13** [comment]
@glav sorry to be a pain, but I have just tried to take the new 4.3.0 version of the package for a spin, but it neither the `Glav.CacheAdapter` or the `Glav.CacheAdapter.Core` packages seem to contain any dll's.  Opening both of the packages within NuGet Explorer show only the license.txt files and the example files:

![image](https://user-images.githubusercontent.com/1271146/112000444-e8214280-8b15-11eb-81f5-7632dfcfbb8c.png)

Can you confirm if this is also happening for you?  Thanks

**Comment by gep13** [comment]
In the previous release, looks like the assembly was contained within the `lib` folder in the `Glav.CacheAdapter.Core` package:

![image](https://user-images.githubusercontent.com/1271146/112002258-9974a800-8b17-11eb-8ccc-7fb860cb94b1.png)

**Comment by glav** [comment]
Oh, I definitely tested it locally prior to upload. Let me have a look

**Comment by glav** [comment]
Should be rersolved now. Closing this and will leave #21 open until verified.
