### ISSUE TITLE
Why there's a separate nugets for Glav.CacheAdapter.Core?

### ISSUE THREAD

**Issue by serhioV** [glav/Glav.CacheAdapter#9]
Why there's a two separate nugets Glav.CacheAdapter.Core and Glav.CacheAdapter pointing to the same GitHub project and having the same output dll? 

this is confusing do not say more.

**Comment by glav** [comment]
Same project for both but one package definition just contains more. Core contains just DLL's, no readme, no example code etc as people who had already installed the package and simply wanted to upgrade, did not want the example code, readme etc to be installed all the time and have to go delete it each time they upgraded.

**Comment by serhioV** [comment]
this file readme adds and removes itself from time to time from/to the solution... 
very annoing, strange nuget management, who does really read a readme in the solution? this readme and code examples should be in the GitHub to download or read a part... 

Why does I need that in my solution?


If every nuget author will add .cs files and samples, examples, readmefiles, what will became a user project that having sometimes tens of nugets? What if another guy will add another readme.txt?

**Comment by ferventcoder** [comment]
@serhioV sounds like you should just install Glav.CacheAdapter.Core and you'll be good to go.

**Comment by glav** [comment]
@serhioV,  @ferventcoder is correct. The Glav.CacheAdapter.Core has only the binaries and no readme and acts as a dependency for Glav.CacheAdapter (full version).
